intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import libs += libcrails%lib{crails}

lib{crails-xmlrpc}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-xmlrpc}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-xmlrpc}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-xmlrpc}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-xmlrpc}: bin.lib.version = "-$version.project_id"
else
  lib{crails-xmlrpc}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/crails/
  install.subdirs = true
}
