intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import libs += libcrails%lib{crails}
import libs += libcrails-controllers%lib{crails-controllers}
import libs += libcrails-http-client%lib{crails-http-client}

lib{crails-xmlrpc}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-xmlrpc}:
{
  cxx.export.poptions = "-I$out_root/libcrails-xmlrpc" "-I$src_root/libcrails-xmlrpc"
  cxx.export.libs = $intf_libs
}

liba{crails-xmlrpc}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-xmlrpc}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-xmlrpc}: bin.lib.version = "-$version.project_id"
else
  lib{crails-xmlrpc}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
